#!/bin/bash
# OpenLLM Toolkit - Demo Script
# Shows practical examples for beginners

set -e

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${BLUE}🤖 OpenLLM Toolkit Demo${NC}"
echo -e "${BLUE}Let's see what your free AI assistant can do!${NC}"
echo ""

# Check if openllm is available
if ! command -v openllm &> /dev/null; then
    echo -e "${RED}❌ OpenLLM Toolkit not found!${NC}"
    echo -e "${YELLOW}Please run the quick start script first:${NC}"
    echo "curl -fsSL https://raw.githubusercontent.com/Sourcesiri-Kamelot/swiftagent/main/Scripts/quick_start.sh | bash"
    exit 1
fi

# Function to run demo with delay
run_demo() {
    local title="$1"
    local command="$2"
    local description="$3"
    
    echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${GREEN}🎯 Demo: $title${NC}"
    echo -e "${YELLOW}$description${NC}"
    echo ""
    echo -e "${BLUE}Running: $command${NC}"
    echo ""
    
    # Run the command
    eval "$command"
    
    echo ""
    echo -e "${GREEN}✅ Demo completed!${NC}"
    echo ""
    read -p "Press Enter to continue to the next demo..."
    echo ""
}

# Create demo files
setup_demo_files() {
    echo -e "${BLUE}📁 Setting up demo files...${NC}"
    
    # Create demo directory
    mkdir -p ~/Documents/openllm-demo
    
    # Create a sample text file
    cat > ~/Documents/openllm-demo/sample.txt << 'EOF'
OpenLLM Toolkit Demo File

This is a sample text file to demonstrate the file reading capabilities.
The toolkit can read, write, and manage files safely.

Features demonstrated:
- File reading
- Text processing
- Content analysis
EOF

    # Create a simple image (if ImageMagick is available)
    if command -v convert &> /dev/null; then
        convert -size 400x200 xc:lightblue -pointsize 20 -gravity center \
                -draw "text 0,0 'OpenLLM Toolkit\nDemo Image'" \
                ~/Documents/openllm-demo/demo.png
    else
        # Create a simple text file as image placeholder
        echo "This would be an image file in a real demo" > ~/Documents/openllm-demo/demo.png
    fi
    
    echo -e "${GREEN}✅ Demo files created in ~/Documents/openllm-demo/${NC}"
    echo ""
}

# Demo 1: Basic chat
demo_chat() {
    run_demo \
        "AI Chat" \
        "openllm chat 'Write a short poem about artificial intelligence'" \
        "Show how to have a conversation with the AI assistant"
}

# Demo 2: File operations
demo_files() {
    run_demo \
        "File Reading" \
        "openllm read ~/Documents/openllm-demo/sample.txt" \
        "Demonstrate reading and analyzing text files"
}

# Demo 3: File writing
demo_write() {
    run_demo \
        "File Writing" \
        "openllm write ~/Documents/openllm-demo/ai_response.txt 'This is a response generated by the AI assistant. The OpenLLM Toolkit makes it easy to work with files and get AI-powered insights.'" \
        "Show how to write content to files using AI"
}

# Demo 4: Directory listing
demo_list() {
    run_demo \
        "Directory Listing" \
        "openllm list ~/Documents/openllm-demo" \
        "Demonstrate listing files in a directory"
}

# Demo 5: File search
demo_search() {
    run_demo \
        "File Search" \
        "openllm search 'demo' ~/Documents" \
        "Show how to search for files containing specific text"
}

# Demo 6: System status
demo_status() {
    run_demo \
        "System Status" \
        "openllm status" \
        "Check the status of AI providers and system components"
}

# Demo 7: Provider list
demo_providers() {
    run_demo \
        "Available Providers" \
        "openllm providers" \
        "Show which AI providers are available and their status"
}

# Demo 8: Interactive mode
demo_interactive() {
    echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${GREEN}🎯 Demo: Interactive Mode${NC}"
    echo -e "${YELLOW}Start the interactive chat mode where you can have a conversation with the AI${NC}"
    echo ""
    echo -e "${BLUE}Starting interactive mode...${NC}"
    echo -e "${YELLOW}Type 'exit' to quit the interactive mode${NC}"
    echo ""
    
    openllm
}

# Show help
show_help() {
    echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${GREEN}📚 Available Commands${NC}"
    echo ""
    echo -e "${BLUE}Chat Commands:${NC}"
    echo "  openllm chat 'your message'     # Quick chat with AI"
    echo "  openllm                         # Start interactive mode"
    echo ""
    echo -e "${BLUE}File Commands:${NC}"
    echo "  openllm read file.txt           # Read and analyze a file"
    echo "  openllm write file.txt 'text'   # Write content to a file"
    echo "  openllm list directory          # List files in directory"
    echo "  openllm search 'text' dir       # Search for files"
    echo ""
    echo -e "${BLUE}Image Commands:${NC}"
    echo "  openllm photo image.jpg         # Analyze an image"
    echo "  openllm text image.png          # Extract text from image"
    echo "  openllm describe image.jpg      # Get AI description"
    echo ""
    echo -e "${BLUE}System Commands:${NC}"
    echo "  openllm status                  # Check system status"
    echo "  openllm providers               # List available AI providers"
    echo "  openllm help                    # Show this help"
    echo ""
}

# Main demo flow
main() {
    echo -e "${GREEN}Welcome to the OpenLLM Toolkit Demo!${NC}"
    echo -e "${YELLOW}This demo will show you the key features of your free AI assistant.${NC}"
    echo ""
    
    # Setup demo files
    setup_demo_files
    
    # Run demos
    demo_chat
    demo_files
    demo_write
    demo_list
    demo_search
    demo_status
    demo_providers
    
    # Ask if user wants to try interactive mode
    echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${GREEN}🎯 Try Interactive Mode?${NC}"
    echo -e "${YELLOW}Would you like to try the interactive chat mode? (y/n)${NC}"
    read -p "Your choice: " choice
    
    if [[ $choice =~ ^[Yy]$ ]]; then
        demo_interactive
    fi
    
    # Show help
    show_help
    
    echo ""
    echo -e "${GREEN}🎉 Demo completed!${NC}"
    echo -e "${BLUE}You now know how to use your free AI assistant.${NC}"
    echo ""
    echo -e "${YELLOW}Next steps:${NC}"
    echo "• Try your own commands"
    echo "• Explore the help system: openllm help"
    echo "• Join our community for support"
    echo ""
    echo -e "${BLUE}Happy AI-ing! 🚀${NC}"
}

# Run main function
main "$@" 